name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: "test / ${{ matrix.ruby }}"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: [ "3.2", "3.3", "3.4", head ]

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec rake test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4

  # See: https://github.com/orgs/community/discussions/26822#discussioncomment-3305794
  test-finale:
    name: "test"

    runs-on: ubuntu-latest
    if: ${{ always() }}

    needs: [test]

    steps:
      - run: test "success" = "${{ needs.test.result }}"

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true

      - run: bundle exec rake lint
